name: "🐛 Bug Report"
description: Report an issue or possible bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure there's no existing issue regarding this bug already.
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Please write a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log file
      description: Your _BandcampDownloader.log_ file
      placeholder: Please upload your whole log file, do not merely paste some part of it.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
