//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandcampDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BandcampDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowCircle225Left {
            get {
                object obj = ResourceManager.GetObject("ArrowCircle225Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string buttonBrowse {
            get {
                return ResourceManager.GetString("buttonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for folder.
        /// </summary>
        internal static string buttonBrowse_ToolTip {
            get {
                return ResourceManager.GetString("buttonBrowse_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check no_w.
        /// </summary>
        internal static string buttonCheckForUpdates {
            get {
                return ResourceManager.GetString("buttonCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Download update.
        /// </summary>
        internal static string buttonDownloadUpdate {
            get {
                return ResourceManager.GetString("buttonDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        internal static string buttonOpenSettingsWindow {
            get {
                return ResourceManager.GetString("buttonOpenSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        internal static string buttonOpenSettingsWindow_ToolTip {
            get {
                return ResourceManager.GetString("buttonOpenSettingsWindow_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets settings to their default values.
        /// </summary>
        internal static string buttonResetSettings_ToolTip {
            get {
                return ResourceManager.GetString("buttonResetSettings_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        internal static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start _download.
        /// </summary>
        internal static string buttonStart {
            get {
                return ResourceManager.GetString("buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string buttonStop {
            get {
                return ResourceManager.GetString("buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        internal static string buttonViewChangelog {
            get {
                return ResourceManager.GetString("buttonViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not download changelog from {0}.
        /// </summary>
        internal static string changelogDownloadError {
            get {
                return ResourceManager.GetString("changelogDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for _updates at startup.
        /// </summary>
        internal static string checkBoxCheckForUpdates {
            get {
                return ResourceManager.GetString("checkBoxCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the application will query the following address when starting:.
        /// </summary>
        internal static string checkBoxCheckForUpdates_ToolTip_Part {
            get {
                return ResourceManager.GetString("checkBoxCheckForUpdates_ToolTip_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to _jpg.
        /// </summary>
        internal static string checkBoxCoverArtInFolderConvertToJpg {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderConvertToJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the cover art will be converted to jpg with a jpeg compression of 90 (which is an excellent tradeoff between size and perfection)..
        /// </summary>
        internal static string checkBoxCoverArtInFolderConvertToJpg_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderConvertToJpg_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain _maximum width/height.
        /// </summary>
        internal static string checkBoxCoverArtInFolderResize {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the cover art will be resized with the specified max width/height..
        /// </summary>
        internal static string checkBoxCoverArtInFolderResize_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInFolderResize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to jp_g.
        /// </summary>
        internal static string checkBoxCoverArtInTagsConvertToJpg {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsConvertToJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the cover art will be converted to jpg with a jpeg compression of 90 (which is an excellent tradeoff between size and perfection)..
        /// </summary>
        internal static string checkBoxCoverArtInTagsConvertToJpg_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsConvertToJpg_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain m_aximum width/height.
        /// </summary>
        internal static string checkBoxCoverArtInTagsResize {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the cover art will be resized with the specified max width/height..
        /// </summary>
        internal static string checkBoxCoverArtInTagsResize_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCoverArtInTagsResize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create _playlist for each album.
        /// </summary>
        internal static string checkBoxCreatePlaylist {
            get {
                return ResourceManager.GetString("checkBoxCreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, a file containing the album tracks will be created for each downloaded album..
        /// </summary>
        internal static string checkBoxCreatePlaylist_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxCreatePlaylist_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download _artist discography.
        /// </summary>
        internal static string checkBoxDownloadDiscography {
            get {
                return ResourceManager.GetString("checkBoxDownloadDiscography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the whole artist discography will be downloaded..
        /// </summary>
        internal static string checkBoxDownloadDiscography_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxDownloadDiscography_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play _notifications sounds.
        /// </summary>
        internal static string checkBoxEnableApplicationSounds {
            get {
                return ResourceManager.GetString("checkBoxEnableApplicationSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, a notification sound will be played when downloads are finished..
        /// </summary>
        internal static string checkBoxEnableApplicationSounds_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxEnableApplicationSounds_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use _extended format (for M3U only).
        /// </summary>
        internal static string checkBoxM3uExtended {
            get {
                return ResourceManager.GetString("checkBoxM3uExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the extended format (directives prefaced by the # character) will be used when creating M3U playlists..
        /// </summary>
        internal static string checkBoxM3uExtended_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxM3uExtended_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Modify tracks tags (ID3).
        /// </summary>
        internal static string checkBoxModifyTags {
            get {
                return ResourceManager.GetString("checkBoxModifyTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, each tag will be modified as specified below.
        ///
        ///If unchecked, all settings below will be ignored and the tags will be left as they are in the original downloaded file.
        ///This is equivalent to setting &quot;Do not modify&quot; on each tag..
        /// </summary>
        internal static string checkBoxModifyTags_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxModifyTags_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Download one album at a time.
        /// </summary>
        internal static string checkBoxOneAlbumAtATime {
            get {
                return ResourceManager.GetString("checkBoxOneAlbumAtATime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, only one album at a time will be downloaded.
        ///If unchecked, all albums will be downloaded at the same time (preferred if you have a high bandwidth)..
        /// </summary>
        internal static string checkBoxOneAlbumAtATime_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxOneAlbumAtATime_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve files _size before downloading tracks.
        /// </summary>
        internal static string checkBoxRetrieveFilesSize {
            get {
                return ResourceManager.GetString("checkBoxRetrieveFilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, files size will be retrieved so that precise download progress can be shown.
        ///Uncheck this option to save some time..
        /// </summary>
        internal static string checkBoxRetrieveFilesSize_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxRetrieveFilesSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in _folder.
        /// </summary>
        internal static string checkBoxSaveCoverArtInFolder {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the cover art will be downloaded in the albums folder..
        /// </summary>
        internal static string checkBoxSaveCoverArtInFolder_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in _tags.
        /// </summary>
        internal static string checkBoxSaveCoverArtInTags {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the cover art will be saved in the tracks tags..
        /// </summary>
        internal static string checkBoxSaveCoverArtInTags_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxSaveCoverArtInTags_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _verbose log.
        /// </summary>
        internal static string checkBoxVerboseLog {
            get {
                return ResourceManager.GetString("checkBoxVerboseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, more information will be shown on the log..
        /// </summary>
        internal static string checkBoxVerboseLog_ToolTip {
            get {
                return ResourceManager.GetString("checkBoxVerboseLog_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cloud {
            get {
                object obj = ResourceManager.GetObject("Cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CloudIco {
            get {
                object obj = ResourceManager.GetObject("CloudIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExclamationSmall {
            get {
                object obj = ResourceManager.GetObject("ExclamationSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder to save albums.
        /// </summary>
        internal static string folderBrowserDialogDescription {
            get {
                return ResourceManager.GetString("folderBrowserDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InformationSmallWhite {
            get {
                object obj = ResourceManager.GetObject("InformationSmallWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change these settings at your own risk..
        /// </summary>
        internal static string labelAdvancedSettingsWarning {
            get {
                return ResourceManager.GetString("labelAdvancedSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album art_ist.
        /// </summary>
        internal static string labelAlbumArtist {
            get {
                return ResourceManager.GetString("labelAlbumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album _name.
        /// </summary>
        internal static string labelAlbumTitle {
            get {
                return ResourceManager.GetString("labelAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed file _size difference (%).
        /// </summary>
        internal static string labelAllowedFileSizeDifference {
            get {
                return ResourceManager.GetString("labelAllowedFileSizeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Artist.
        /// </summary>
        internal static string labelArtist {
            get {
                return ResourceManager.GetString("labelArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset settings.
        /// </summary>
        internal static string labelButtonResetSettings {
            get {
                return ResourceManager.GetString("labelButtonResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string labelChangelog {
            get {
                return ResourceManager.GetString("labelChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string labelChangelogTitle {
            get {
                return ResourceManager.GetString("labelChangelogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comm_ents.
        /// </summary>
        internal static string labelComments {
            get {
                return ResourceManager.GetString("labelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File _name format.
        /// </summary>
        internal static string labelCoverArtFileNameFormat {
            get {
                return ResourceManager.GetString("labelCoverArtFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max size (_px).
        /// </summary>
        internal static string labelCoverArtInFolderMaxSize {
            get {
                return ResourceManager.GetString("labelCoverArtInFolderMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max size (p_x).
        /// </summary>
        internal static string labelCoverArtInTagsMaxSize {
            get {
                return ResourceManager.GetString("labelCoverArtInTagsMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version:.
        /// </summary>
        internal static string labelCurrentVersion {
            get {
                return ResourceManager.GetString("labelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download _max tries.
        /// </summary>
        internal static string labelDownloadMaxTries {
            get {
                return ResourceManager.GetString("labelDownloadMaxTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry c_ooldown (sec).
        /// </summary>
        internal static string labelDownloadRetryCooldown {
            get {
                return ResourceManager.GetString("labelDownloadRetryCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry _exponent.
        /// </summary>
        internal static string labelDownloadRetryExponent {
            get {
                return ResourceManager.GetString("labelDownloadRetryExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save albums _to.
        /// </summary>
        internal static string labelDownloadsPath {
            get {
                return ResourceManager.GetString("labelDownloadsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File name format:.
        /// </summary>
        internal static string labelFileNameFormat {
            get {
                return ResourceManager.GetString("labelFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _HTTP(S) proxy.
        /// </summary>
        internal static string labelHttp {
            get {
                return ResourceManager.GetString("labelHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Port.
        /// </summary>
        internal static string labelHttpPort {
            get {
                return ResourceManager.GetString("labelHttpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        internal static string labelIssues {
            get {
                return ResourceManager.GetString("labelIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        internal static string labelLanguage {
            get {
                return ResourceManager.GetString("labelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string labelListBoxItemAbout {
            get {
                return ResourceManager.GetString("labelListBoxItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        internal static string labelListBoxItemAdvanced {
            get {
                return ResourceManager.GetString("labelListBoxItemAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover art.
        /// </summary>
        internal static string labelListBoxItemCoverArt {
            get {
                return ResourceManager.GetString("labelListBoxItemCoverArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string labelListBoxItemDownloads {
            get {
                return ResourceManager.GetString("labelListBoxItemDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string labelListBoxItemGeneral {
            get {
                return ResourceManager.GetString("labelListBoxItemGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string labelListBoxItemNetwork {
            get {
                return ResourceManager.GetString("labelListBoxItemNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string labelListBoxItemPlaylist {
            get {
                return ResourceManager.GetString("labelListBoxItemPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naming and tags.
        /// </summary>
        internal static string labelListBoxItemTags {
            get {
                return ResourceManager.GetString("labelListBoxItemTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Lyrics.
        /// </summary>
        internal static string labelLyrics {
            get {
                return ResourceManager.GetString("labelLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File _name format.
        /// </summary>
        internal static string labelPlaylistFileNameFormat {
            get {
                return ResourceManager.GetString("labelPlaylistFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist _format.
        /// </summary>
        internal static string labelPlaylistFormat {
            get {
                return ResourceManager.GetString("labelPlaylistFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some settings cannot be changed while tracks are downloading..
        /// </summary>
        internal static string labelSettingsInfo {
            get {
                return ResourceManager.GetString("labelSettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track n_umber.
        /// </summary>
        internal static string labelTrackNumber {
            get {
                return ResourceManager.GetString("labelTrackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Title.
        /// </summary>
        internal static string labelTrackTitle {
            get {
                return ResourceManager.GetString("labelTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (the log file is always verbose).
        /// </summary>
        internal static string labelVerboseLogInfo {
            get {
                return ResourceManager.GetString("labelVerboseLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string labelVersion {
            get {
                return ResourceManager.GetString("labelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check for updates.
        /// </summary>
        internal static string labelVersionError {
            get {
                return ResourceManager.GetString("labelVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available.
        /// </summary>
        internal static string labelVersionNewUpdateAvailable {
            get {
                return ResourceManager.GetString("labelVersionNewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string labelWebsite {
            get {
                return ResourceManager.GetString("labelWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album release _year.
        /// </summary>
        internal static string labelYear {
            get {
                return ResourceManager.GetString("labelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string messageBoxButtonCancel {
            get {
                return ResourceManager.GetString("messageBoxButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        internal static string messageBoxButtonNo {
            get {
                return ResourceManager.GetString("messageBoxButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string messageBoxButtonOK {
            get {
                return ResourceManager.GetString("messageBoxButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        internal static string messageBoxButtonYes {
            get {
                return ResourceManager.GetString("messageBoxButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to cancel all downloads?.
        /// </summary>
        internal static string messageBoxCancelDownloads {
            get {
                return ResourceManager.GetString("messageBoxCancelDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while checking for updates. Please retry later..
        /// </summary>
        internal static string messageBoxCheckForUpdatesError {
            get {
                return ResourceManager.GetString("messageBoxCheckForUpdatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently active downloads. Are you sure you want to close the application and stop all downloads?.
        /// </summary>
        internal static string messageBoxCloseWindowWhenDownloading {
            get {
                return ResourceManager.GetString("messageBoxCloseWindowWhenDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the latest version available ({0})..
        /// </summary>
        internal static string messageBoxNoUpdateAvailable {
            get {
                return ResourceManager.GetString("messageBoxNoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to their default values?.
        /// </summary>
        internal static string messageBoxResetSettings {
            get {
                return ResourceManager.GetString("messageBoxResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available:
        ///Current version = {0}
        ///Latest version = {1}
        ///
        ///Would you like to go to the project website in order to download the latest version?.
        /// </summary>
        internal static string messageBoxUpdateAvailable {
            get {
                return ResourceManager.GetString("messageBoxUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manual proxy configuration.
        /// </summary>
        internal static string radioButtonManualProxy {
            get {
                return ResourceManager.GetString("radioButtonManualProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No proxy.
        /// </summary>
        internal static string radioButtonNoProxy {
            get {
                return ResourceManager.GetString("radioButtonNoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _System proxy.
        /// </summary>
        internal static string radioButtonSystemProxy {
            get {
                return ResourceManager.GetString("radioButtonSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string saveFileDialogTitle {
            get {
                return ResourceManager.GetString("saveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not modify.
        /// </summary>
        internal static string TagEditAction_DoNotModify {
            get {
                return ResourceManager.GetString("TagEditAction_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty tag.
        /// </summary>
        internal static string TagEditAction_Empty {
            get {
                return ResourceManager.GetString("TagEditAction_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in tag.
        /// </summary>
        internal static string TagEditAction_Modify {
            get {
                return ResourceManager.GetString("TagEditAction_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not modify.
        /// </summary>
        internal static string TagRemoveAction_DoNotModify {
            get {
                return ResourceManager.GetString("TagRemoveAction_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty tag.
        /// </summary>
        internal static string TagRemoveAction_Empty {
            get {
                return ResourceManager.GetString("TagRemoveAction_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases history.
        /// </summary>
        internal static string textBlockReleasesWebsite {
            get {
                return ResourceManager.GetString("textBlockReleasesWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help translate.
        /// </summary>
        internal static string textBlockTranslationHelp {
            get {
                return ResourceManager.GetString("textBlockTranslationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When downloading a track, if the same file (name) already exists, it will be checked against the track to download.
        ///If the size of both files differ from less than this value (in percent), the track download will be skipped.
        ///Set this value to 0 in order to always download tracks, even if already existing on disk.
        ///
        ///Recommended value = 5.
        /// </summary>
        internal static string textBoxAllowedFileSizeDifference_ToolTip {
            get {
                return ResourceManager.GetString("textBoxAllowedFileSizeDifference_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use placeholders to customize the file name:
        ///- {artist} will be replaced by the album artist
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxCoverArtFileNameFormat_ToolTip {
            get {
                return ResourceManager.GetString("textBoxCoverArtFileNameFormat_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of tries performed to download a track if it fails.
        ///After that number is reached (for each track), the track download will be skipped.
        ///
        ///Recommended value = 7.
        /// </summary>
        internal static string textBoxDownloadMaxTries_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadMaxTries_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to control the exponential back-off mechanism.
        ///After each failure of a track download, BandcampDownloader can wait for a specific time before trying again
        ///to download the track in order to avoid tickling the Bandcamp anti-spam filter.
        ///The formula used to compute the time to wait before trying again a download is the following:
        ///time = cooldown * (exponent ^ try-count)
        ///
        ///Recommended value = 0.2.
        /// </summary>
        internal static string textBoxDownloadRetryCooldown_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadRetryCooldown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to control the exponential back-off mechanism.
        ///After each failure of a track download, BandcampDownloader can wait for a specific time before trying again 
        ///to download the track in order to avoid tickling the Bandcamp anti-spam filter.
        ///The formula used to compute the time to wait before trying again a download is the following:
        ///time = cooldown * (exponent ^ try-count)
        ///
        ///Recommended value = 4.
        /// </summary>
        internal static string textBoxDownloadRetryExponent_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadRetryExponent_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use placeholders to customize the download folder depending on the album:
        ///- {artist} will be replaced by the album artist
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxDownloadsPath_ToolTip {
            get {
                return ResourceManager.GetString("textBoxDownloadsPath_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use placeholders to customize the file name:
        ///- {artist} will be replaced by the album artist
        ///- {title} will be replaced by the track name
        ///- {tracknum} will be replaced by the track number
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxFileNameFormat_ToolTip {
            get {
                return ResourceManager.GetString("textBoxFileNameFormat_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use placeholders to customize the file name:
        ///- {artist} will be replaced by the album artist
        ///- {album} will be replaced by the album name
        ///- {year}, {month} and {day} will be replaced by the album release date.
        /// </summary>
        internal static string textBoxPlaylistFileNameFormat_ToolTip {
            get {
                return ResourceManager.GetString("textBoxPlaylistFileNameFormat_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste URLs of albums to download here. You can specify multiple URLs by writing one URL per line.
        ///
        ///A Bandcamp URL looks like: http://[artist].bandcamp.com/album/[album] or http://[artist].bandcamp.com/track/[track]
        ///Paste artist pages: http://[artist].bandcamp.com and check &quot;☑ Download artist discography&quot; to download all their albums..
        /// </summary>
        internal static string textBoxUrlsPlaceholder {
            get {
                return ResourceManager.GetString("textBoxUrlsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string windowSettings_Title {
            get {
                return ResourceManager.GetString("windowSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string windowUpdate_Title {
            get {
                return ResourceManager.GetString("windowUpdate_Title", resourceCulture);
            }
        }
    }
}
